### PR TITLE
Implemented `gcapc-path` configuration.

### LINKED ISSUE #31: Add configuration value for the path to the repository
Currently the plugin assume that the content directory is a separate repository. I don't see a good reason for that, so I would like to use the complete site as a repository. 

I would create a pull request that implements a configuration option for the path to the repository, if you would accept it. :)

### PR DESCRIPTION
**Pull request by tobiastom**
This closes #31.

### CODE REVIEW

**Comment by Pascalmh** [comment]
@tobiastom thank you! Same as in PR #34 - could you change the commit message to something like:

> feat: add gcapc-path option

**Comment by tobiastom** [comment]
Updated the commit message. :)

**Comment by tobiastom** [comment]
Cool! Thank you for merging it! 

Any idea when you might release it?

**Comment by Pascalmh** [comment]
Version 1.5.0 is release - you should be able to download it (also via composer) - thank you for your contribution :)

**Pull request merged**
