### PR TITLE
Added Site Update-Hook; Added optional User-Hooks

### LINKED ISSUE #46: Not working when `site.txt` is changed
Maybe Kirby doesn't fire any hooks for the site-settings or what else could be the problem? And when I save any other page after I've modified `site.txt` (via *Menu > Settings*) it commits & pushes all changes together.

bildschirmfoto 2017-08-19 um 12 36 17

Dennis

### PR DESCRIPTION
**Pull request by wottpal**
* Fixes #46 
* ~~Adding the option to listen to user- and avatar-events as opt-in.~~

### CODE REVIEW

**Comment by Pascalmh** [comment]
@wottpal thank you for your contribution :) could you split the changes and create a seperate PR for the User changes (individual commits would be great here because those are two different changes).

Also the [Options](https://github.com/blankogmbh/kirby-git-commit-and-push-content#options) should be extended by the new variable for user hooks then :)

If you pull out the user changes I am more then happy to merge this request!

**Comment by wottpal** [comment]
They are reverted for now :)

**Comment by wottpal** [comment]
Nice ;) BTW why do you make an extra branch for each feature/fix?

**Comment by Pascalmh** [comment]
Its a concept called "feature branching" we basically use it to put features/fixes live as soon as possible :)

- https://confluence.atlassian.com/bitbucket/workflow-for-git-feature-branching-814201830.html
- https://docs.gitlab.com/ee/university/training/topics/feature_branching.html
- https://guides.github.com/introduction/flow/

**Pull request merged**
