### PR TITLE
Update package.json.

### PR DESCRIPTION
**Pull request by shimikano**
Add "type": "kirby-plugin" to allow installation via Kirby CLI.

### CODE REVIEW

**Comment by Pascalmh** [comment]
@shimikano have you tried this? Will this install the Submodule (Git.php) as well?

**Comment by shimikano** [comment]
@Pascalmh You're right - it does _not_ install the Submodule...

**Comment by shimikano** [comment]
I couldn't come up with a nice way as to integrate the submodule as part of the Kirby CLI plugin installation procedure, so you may close this PR if you want.

In general though, when it comes to managing the dependencies of a Kirby plugin, I'd probably rather opt for fixed versions of the dependencies in my repository - as opposed to a submodule setup. This would result in better control and reproducibility and not have an update to a dependency potentially break your plugin.

Anyway, thank you for this cool plugin :)

**Comment by Pascalmh** [comment]
Thank you anyway :) 

I would suggest using Composer whenever you can to install plugins and also kirby itself. You get the fixes and improvements of the dependencies (e.g. if https://github.com/filp/whoops - which is a dependency of kirby - gets a bugfix you can get it without the need of the kirby developers to make a new kirby release).

**Pull request closed without merging**
